-- Seed 100 question cards (PT-BR). Each insert is keyed on the text via a
-- unique check so re-running is idempotent.
create unique index if not exists "questions_text_unique" on questions ((lower(btrim(text))));

insert into questions (text) values
  -- Íntimas / memória / infância (25)
  ('Qual foi o lugar onde morei por mais tempo?'),
  ('Qual o nome do meu primeiro animal de estimação?'),
  ('Qual foi o melhor presente que já recebi?'),
  ('Qual a maior vergonha da minha infância?'),
  ('Qual o nome do meu primeiro amor?'),
  ('Qual foi a primeira coisa que quis ser quando crescer?'),
  ('Qual professor eu nunca esqueci?'),
  ('Qual foi o último livro que terminei?'),
  ('Qual cidade eu mais quero conhecer antes de morrer?'),
  ('Qual o som que mais me lembra a infância?'),
  ('Qual foi o primeiro show que assisti?'),
  ('Qual cheiro me transporta no tempo?'),
  ('Qual a comida da minha avó que eu mais sinto falta?'),
  ('Qual o melhor abraço que já recebi?'),
  ('Qual foi o último filme que me fez chorar?'),
  ('Qual segredo eu nunca contei a ninguém?'),
  ('Qual foi a viagem que mudou minha vida?'),
  ('Qual era o brinquedo favorito da minha infância?'),
  ('Qual a música que tocou no meu primeiro beijo?'),
  ('Qual foi o sonho mais estranho que já tive?'),
  ('Qual frase do meu pai/mãe eu nunca esqueci?'),
  ('Qual amigo eu mais sinto falta?'),
  ('Qual foi a melhor festa que já fui?'),
  ('Qual foi o pior dia da minha vida?'),
  ('Qual a maior decisão que já tomei?'),

  -- Divertidas / absurdas (25)
  ('Se eu fosse um animal, qual seria?'),
  ('Qual super-herói eu seria no fim de semana?'),
  ('Qual seria meu nome de DJ?'),
  ('Qual prato eu inventaria num restaurante?'),
  ('Qual seria meu apelido numa luta livre?'),
  ('Qual emoji me representa hoje?'),
  ('Qual seria minha música tema entrando no salão?'),
  ('Qual personagem de desenho me parece comigo?'),
  ('Se eu virasse comida, qual seria?'),
  ('Qual seria meu nome artístico se fosse cantor?'),
  ('Qual a coisa mais ridícula que já comprei?'),
  ('Qual conspiração eu acho que é verdade?'),
  ('Qual seria o título de um filme sobre minha vida?'),
  ('Qual o meu maior talento inútil?'),
  ('Qual seria minha última refeição?'),
  ('Qual personagem de série eu daria um soco?'),
  ('Qual som eu fazia quando criança e ninguém entendia?'),
  ('Qual o meu poder secreto inútil?'),
  ('Se eu fosse um doce, qual seria?'),
  ('Qual o nome da minha banda imaginária?'),
  ('Qual frase eu repito demais sem perceber?'),
  ('Qual seria meu codinome num filme de espionagem?'),
  ('Qual planta eu seria se eu virasse uma?'),
  ('Qual a mentira mais boba que já contei?'),
  ('Qual seria meu hobby se eu tivesse tempo?'),

  -- Hipotéticas / polarizadoras (25)
  ('Qual época eu viajaria no tempo?'),
  ('Qual lugar eu nunca moraria?'),
  ('Qual celebridade eu não suporto?'),
  ('Qual filme superestimado todo mundo ama?'),
  ('Qual comida eu odeio mas todo mundo adora?'),
  ('Qual hábito alheio me tira do sério?'),
  ('Qual app eu apagaria do mundo?'),
  ('Qual estação do ano é melhor?'),
  ('Qual gênero musical eu não suporto?'),
  ('Qual rede social eu fecharia para sempre?'),
  ('Qual lugar do mundo eu acho mais lindo?'),
  ('Qual super-poder eu queria ter?'),
  ('Qual cor define minha personalidade?'),
  ('Qual cidade brasileira eu fugiria de viver?'),
  ('Qual estilo de música rola no meu funeral?'),
  ('Qual é o pior emprego possível pra mim?'),
  ('Qual herói da história eu trocaria de lugar por um dia?'),
  ('Qual desenho animado é arte de verdade?'),
  ('Qual período da minha vida eu reviveria?'),
  ('Qual época eu não voltaria nem morto?'),
  ('Qual final de série me deixou furioso?'),
  ('Qual lugar eu visitaria se fosse invisível?'),
  ('Qual filme eu assistiria em loop pra sempre?'),
  ('Qual decisão eu tomaria diferente se pudesse?'),
  ('Qual pessoa famosa morta eu jantaria hoje?'),

  -- Cotidiano / preferências (25)
  ('Qual o primeiro app que abro de manhã?'),
  ('Qual o meu lanche favorito da madrugada?'),
  ('Qual minha bebida pra todo dia?'),
  ('Qual cheiro eu adoro que ninguém entende?'),
  ('Qual a parte do dia que mais gosto?'),
  ('Qual rotina eu gostaria de ter?'),
  ('Qual cômodo da casa é o meu favorito?'),
  ('Qual a primeira coisa que faço quando chego em casa?'),
  ('Qual meu ritual antes de dormir?'),
  ('Qual minha música pra acordar?'),
  ('Qual playlist tocou mais essa semana?'),
  ('Qual roupa eu uso quando ninguém está vendo?'),
  ('Qual rede social ocupa minha mente?'),
  ('Qual youtuber eu acompanho de longe?'),
  ('Qual marca eu sou fiel sem motivo?'),
  ('Qual lanche da escola eu nunca esqueci?'),
  ('Qual o meu lugar pra pensar a vida?'),
  ('Qual hábito secreto eu tenho?'),
  ('Qual meu drink padrão num bar?'),
  ('Qual livro eu finjo que li?'),
  ('Qual minha série atual viciante?'),
  ('Qual meu transporte favorito na cidade?'),
  ('Qual minha desculpa preferida pra cancelar plano?'),
  ('Qual a comida que peço quando não sei o que comer?'),
  ('Qual frase eu uso pra encerrar conversa chata?')
on conflict do nothing;
